-- Configuración reversible para la pantalla de inicio. No modifica ni elimina datos existentes.
create table if not exists public.home_sections (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  title text,
  subtitle text,
  is_active boolean not null default true,
  visibility_mode text not null default 'automatic' check (visibility_mode in ('active','inactive','automatic')),
  display_order integer not null default 0,
  display_type text not null default 'grid',
  item_limit integer not null default 8 check (item_limit between 1 and 50),
  show_view_all boolean not null default true,
  destination text,
  start_at timestamptz,
  end_at timestamptz,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint home_sections_dates check (end_at is null or start_at is null or end_at > start_at)
);
create table if not exists public.home_banners (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  eyebrow text,
  image_url text not null,
  mobile_image_url text,
  alt_text text not null default '',
  button_text text,
  destination_type text,
  destination_value text,
  text_position text not null default 'left',
  is_active boolean not null default true,
  display_order integer not null default 0,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint home_banners_dates check (end_at is null or start_at is null or end_at > start_at)
);
create table if not exists public.featured_categories (
  id bigint generated by default as identity primary key,
  category_name text not null,
  image_url text not null,
  alt_text text not null default '',
  display_order integer not null default 0,
  is_active boolean not null default true,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint featured_categories_dates check (end_at is null or start_at is null or end_at > start_at)
);
create index if not exists home_sections_active_order_idx on public.home_sections (is_active, display_order);
create index if not exists home_banners_active_dates_order_idx on public.home_banners (is_active, start_at, end_at, display_order);
create index if not exists featured_categories_active_dates_order_idx on public.featured_categories (is_active, start_at, end_at, display_order);
alter table public.home_sections enable row level security;
alter table public.home_banners enable row level security;
alter table public.featured_categories enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'home_sections'
      and policyname = 'Public reads visible home sections'
  ) then
    execute $policy$
      create policy "Public reads visible home sections"
      on public.home_sections for select using (is_active = true)
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'home_banners'
      and policyname = 'Public reads active home banners'
  ) then
    execute $policy$
      create policy "Public reads active home banners"
      on public.home_banners for select using (is_active = true)
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'featured_categories'
      and policyname = 'Public reads active featured categories'
  ) then
    execute $policy$
      create policy "Public reads active featured categories"
      on public.featured_categories for select using (is_active = true)
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'home_sections'
      and policyname = 'Admins manage home sections'
  ) then
    execute $policy$
      create policy "Admins manage home sections" on public.home_sections for all to authenticated
      using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
      with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'home_banners'
      and policyname = 'Admins manage home banners'
  ) then
    execute $policy$
      create policy "Admins manage home banners" on public.home_banners for all to authenticated
      using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
      with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'featured_categories'
      and policyname = 'Admins manage featured categories'
  ) then
    execute $policy$
      create policy "Admins manage featured categories" on public.featured_categories for all to authenticated
      using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
      with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
    $policy$;
  end if;
end
$$;
insert into public.home_sections (section_key,title,visibility_mode,display_order,item_limit) values
 ('hero','Hero','active',10,5),
 ('categories','Categorías destacadas','active',20,5),
 ('new_arrivals','Novedades','automatic',30,8),
 ('reviews','Lo que dicen nuestras clientas','automatic',35,3),
 ('upcoming','Disponible próximamente','automatic',40,8),
 ('community','Comunidad','automatic',80,2),
 ('trust','Compra con confianza','active',90,4)
on conflict (section_key) do nothing;

-- Reversión manual:
-- drop table if exists public.featured_categories;
-- drop table if exists public.home_banners;
-- drop table if exists public.home_sections;
